"""obs-local application package."""

from .aggregator import AggregatedEvent, AggregationOverview, StageStat, aggregate_records, build_request_detail
from .parser import JsonlParser, LogSourceContext, ParsedLogRecord, parse_jsonl_file, parse_jsonl_lines, parse_log_line, parse_timestamp
from .registry import ProjectSpec, RegistrySnapshot, SourceRegistry, SourceSpec, default_state_db_path
from .schemas import (
    AggregationResult,
    AppConfig,
    ErrorSummary,
    HealthResponse,
    ProjectConfig,
    ProjectHealth,
    RequestDetail,
    RequestSummary,
    ServerConfig,
    ServiceHealth,
    SourceConfig,
    SourceHealth,
    StageStats,
    StageTiming,
    StorageConfig,
    TimelineEvent,
)
from .state_store import (
    FileOffsetState,
    ProjectState,
    SQLiteStateStore,
    SnapshotState,
    SourceHealthState,
    SourceState,
)
from .tailer import FileTailer, TailPlan, TailReadResult, TailerError

__all__ = [
    "AggregatedEvent",
    "AggregationOverview",
    "AggregationResult",
    "AppConfig",
    "ErrorSummary",
    "FileOffsetState",
    "FileTailer",
    "HealthResponse",
    "JsonlParser",
    "LogSourceContext",
    "ParsedLogRecord",
    "ProjectConfig",
    "ProjectHealth",
    "ProjectSpec",
    "ProjectState",
    "RegistrySnapshot",
    "RequestDetail",
    "RequestSummary",
    "ServerConfig",
    "ServiceHealth",
    "SourceConfig",
    "SourceHealth",
    "SQLiteStateStore",
    "SnapshotState",
    "StageStat",
    "StageStats",
    "StageTiming",
    "StorageConfig",
    "SourceHealthState",
    "SourceRegistry",
    "SourceSpec",
    "SourceState",
    "TailPlan",
    "TailReadResult",
    "TailerError",
    "TimelineEvent",
    "aggregate_records",
    "build_request_detail",
    "default_state_db_path",
    "parse_jsonl_file",
    "parse_jsonl_lines",
    "parse_log_line",
    "parse_timestamp",
]
