from __future__ import annotations

LIMIT_RERANK_CANDIDATES_STEP = "limit_rerank_candidates"
METADATA_CONSTRAINTS_PRE_RERANK_STEP = "metadata_constraints_pre_rerank"
RERANK_STEP = "rerank"
METADATA_CONSTRAINTS_POST_RERANK_STEP = "metadata_constraints_post_rerank"
LOOKUP_PRIORITIZATION_STEP = "lookup_prioritization"
METADATA_DOCUMENT_SUPPORT_STEP = "metadata_document_support"
DEFINITION_SUBJECT_STEP = "definition_subject"
LOOKUP_DIVERSIFICATION_STEP = "lookup_diversification"
SCORE_FILTER_STEP = "score_filter"
TOP_K_LIMIT_STEP = "top_k_limit"

DEFAULT_RANKING_PIPELINE_STEPS = (
    LIMIT_RERANK_CANDIDATES_STEP,
    METADATA_CONSTRAINTS_PRE_RERANK_STEP,
    RERANK_STEP,
    METADATA_CONSTRAINTS_POST_RERANK_STEP,
    LOOKUP_PRIORITIZATION_STEP,
    METADATA_DOCUMENT_SUPPORT_STEP,
    DEFINITION_SUBJECT_STEP,
    LOOKUP_DIVERSIFICATION_STEP,
    SCORE_FILTER_STEP,
    TOP_K_LIMIT_STEP,
)

KNOWN_RANKING_PIPELINE_STEPS = frozenset(DEFAULT_RANKING_PIPELINE_STEPS)
